
package com.learnwebservices.services.tempconverter;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TempConverterEndpoint", targetNamespace = "http://learnwebservices.com/services/tempconverter")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TempConverterEndpoint {


    /**
     * 
     * @param celsiusToFahrenheitRequest
     * @return
     *     returns com.learnwebservices.services.tempconverter.CelsiusToFahrenheitResponse
     */
    @WebMethod(operationName = "CelsiusToFahrenheit")
    @WebResult(name = "CelsiusToFahrenheitResponse", targetNamespace = "http://learnwebservices.com/services/tempconverter", partName = "CelsiusToFahrenheitResponse")
    public CelsiusToFahrenheitResponse celsiusToFahrenheit(
        @WebParam(name = "CelsiusToFahrenheitRequest", targetNamespace = "http://learnwebservices.com/services/tempconverter", partName = "CelsiusToFahrenheitRequest")
        CelsiusToFahrenheitRequest celsiusToFahrenheitRequest);

    /**
     * 
     * @param fahrenheitToCelsiusRequest
     * @return
     *     returns com.learnwebservices.services.tempconverter.FahrenheitToCelsiusResponse
     */
    @WebMethod(operationName = "FahrenheitToCelsius")
    @WebResult(name = "FahrenheitToCelsiusResponse", targetNamespace = "http://learnwebservices.com/services/tempconverter", partName = "FahrenheitToCelsiusResponse")
    public FahrenheitToCelsiusResponse fahrenheitToCelsius(
        @WebParam(name = "FahrenheitToCelsiusRequest", targetNamespace = "http://learnwebservices.com/services/tempconverter", partName = "FahrenheitToCelsiusRequest")
        FahrenheitToCelsiusRequest fahrenheitToCelsiusRequest);

}
